"""empty message

Revision ID: 1a2534605306
Revises: 780363d251b3
Create Date: 2019-11-25 22:20:59.183159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a2534605306'
down_revision = '780363d251b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('labelset', sa.Text(), nullable=True))
    op.drop_column('dataset', 'lableset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('lableset', mysql.TEXT(), nullable=True))
    op.drop_column('dataset', 'labelset')
    # ### end Alembic commands ###
