"""empty message

Revision ID: 2923a924be67
Revises: dc5b2fb7ca3d
Create Date: 2019-12-02 21:12:03.579546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2923a924be67'
down_revision = 'dc5b2fb7ca3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('header', sa.Text(), nullable=True))
    op.drop_column('dataset', 'extra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('dataset', 'header')
    # ### end Alembic commands ###
