"""empty message

Revision ID: 3c5b1c022db9
Revises: 5b0648657553
Create Date: 2019-11-24 21:39:23.810353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5b1c022db9'
down_revision = '5b0648657553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('compute_mode', sa.String(length=32), nullable=True))
    op.add_column('dataset', sa.Column('lableset', sa.Text(), nullable=True))
    op.drop_index('catalog', table_name='dataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('catalog', 'dataset', ['catalog'], unique=True)
    op.drop_column('dataset', 'lableset')
    op.drop_column('dataset', 'compute_mode')
    # ### end Alembic commands ###
