"""empty message

Revision ID: 4727c742f8e5
Revises: 2923a924be67
Create Date: 2019-12-02 21:24:09.809578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4727c742f8e5'
down_revision = '2923a924be67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('headers', sa.Text(), nullable=True))
    op.drop_column('dataset', 'header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('header', mysql.TEXT(), nullable=True))
    op.drop_column('dataset', 'headers')
    # ### end Alembic commands ###
