"""empty message

Revision ID: 4d304918c97d
Revises: 5809dc1efc64
Create Date: 2019-11-28 22:04:40.624974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d304918c97d'
down_revision = '5809dc1efc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('tag', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'tag')
    # ### end Alembic commands ###
