"""empty message

Revision ID: 5809dc1efc64
Revises: 70230ed19a6b
Create Date: 2019-11-28 21:29:42.898991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5809dc1efc64'
down_revision = '70230ed19a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('extra', sa.Text(), nullable=True))
    op.add_column('dataset', sa.Column('navigate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'navigate')
    op.drop_column('dataset', 'extra')
    # ### end Alembic commands ###
