"""empty message

Revision ID: 600b476f0a16
Revises: 4d304918c97d
Create Date: 2019-11-29 18:39:33.963085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600b476f0a16'
down_revision = '4d304918c97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockset', sa.Column('centroid', sa.Text(), nullable=True))
    op.add_column('blockset', sa.Column('coordinates', sa.Text(), nullable=True))
    op.drop_column('blockset', 'points')
    op.drop_column('blockset', 'center')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockset', sa.Column('center', mysql.TEXT(), nullable=True))
    op.add_column('blockset', sa.Column('points', mysql.TEXT(), nullable=True))
    op.drop_column('blockset', 'coordinates')
    op.drop_column('blockset', 'centroid')
    # ### end Alembic commands ###
