"""empty message

Revision ID: 98ae32fddca9
Revises: 1a2534605306
Create Date: 2019-11-25 22:34:55.471595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98ae32fddca9'
down_revision = '1a2534605306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('mode', sa.String(length=32), nullable=True))
    op.drop_column('dataset', 'compute_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('compute_mode', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('dataset', 'mode')
    # ### end Alembic commands ###
