"""empty message

Revision ID: c29222776b79
Revises: 98ae32fddca9
Create Date: 2019-11-26 21:28:56.634888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c29222776b79'
down_revision = '98ae32fddca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'task_id')
    op.drop_column('dataset', 'labelset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('labelset', mysql.TEXT(), nullable=True))
    op.add_column('dataset', sa.Column('task_id', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
