"""empty message

Revision ID: dc5b2fb7ca3d
Revises: 600b476f0a16
Create Date: 2019-12-01 20:55:49.712165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc5b2fb7ca3d'
down_revision = '600b476f0a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('description', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
